#!/bin/bash

# Define command-line arguments

RESOURCE_TYPE=$1
NAMESPACE=$2

if [[ -z "${RESOURCE_TYPE}" ]]; then
   echo "At least 1 argument required: resource type - pod or node"
   echo "For the pod, you can add a namespace as a secong argument"
   exit 1
fi 

if [[ "${RESOURCE_TYPE}" =~ ^(pod|pods|po)$ ]]; then
    printf "Resource\tNamespace\tName\tCPU\tMemory\n"
elif [[ "${RESOURCE_TYPE}" =~ ^(node|nodes|no)$ ]]; then
    printf "Resource\tName\tCPU\tMemory\n"
fi

# Retrieve resource usage statistics from Kubernetes
kubectl top "${RESOURCE_TYPE}" -n "${NAMESPACE}" | tail -n +2 | while read line
do
  # Extract CPU and memory usage from the output
  if [[ "${RESOURCE_TYPE}" =~ ^(pod|pods|po)$ ]]; then
      NAME=$(echo $line | awk '{print $1}')
      CPU=$(echo $line | awk '{print $2}')
      MEMORY=$(echo $line | awk '{print $3}')
  elif [[ "${RESOURCE_TYPE}" =~ ^(node|nodes|no)$ ]]; then
      NAME=$(echo $line | awk '{print $1}')
      CPU=$(echo $line | awk '{print $2}')
      MEMORY=$(echo $line | awk '{print $4}')
  else
      echo "Resource type ${RESOURCE_TYPE} is not suppported"
  fi

  # Output the statistics to the console
  # "Resource, Namespace, Name, CPU, Memory"
  printf "%s \t %s \t %s \t %s \t %s\n" "$RESOURCE_TYPE" "$NAMESPACE" "$NAME" "$CPU" "$MEMORY" 
done