apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    app: demo
    run: demo
spec:
  containers:
  - name: app
    image: nginx
    ports:
    - name: http
      containerPort: 8000
    livenessProbe:
      httpGet:
        path: /
        port: http
      initialDelaySeconds: 5
      timeoutSeconds: 1
      periodSeconds: 10
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /ready
        port: http
      initialDelaySeconds: 5
      timeoutSeconds: 1
      periodSeconds: 10
      failureThreshold: 3
