apiVersion: v1
kind: Pod
metadata:
  name: app-resource
spec:
  containers:
  - name: app
    image: nginx
    ports:
    - name: http
      containerPort: 8080
    livenessProbe:
      httpGet:
        path: /
        port: http
      initialDelaySeconds: 5
      timeoutSeconds: 1
      periodSeconds: 10
      failureThreshold: 1
    readinessProbe:
      httpGet:
        path: /ready
        port: http
      initialDelaySeconds: 0
      timeoutSeconds: 1
      periodSeconds: 2
      failureThreshold: 3
      successThreshold: 1
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "100m"
        memory: "256Mi"
